### PR TITLE
Add documentation for runpp_pgm

### PR DESCRIPTION
**Pull request by nitbharambe**
Document the PGM power flow option added to pandapower

https://github.com/e2nIEE/pandapower/issues/2076

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@nitbharambe please fix the build error of docs_check

**Comment by rbolgaryn** [comment]
I think the documentation should also mention what what features of the pandapower net model are compatible and which ones are not.

**Comment by rbolgaryn** [comment]
Please let me know when the PR is ready for review

**Comment by nitbharambe** [comment]
@rbolgaryn Yes! It is!

> Please let me know when the PR is ready for review

**Comment by TonyXiang8787** [comment]
@rbolgaryn can you review and merge this? So that this can go with the function itself on time to the next release.

**Review by rbolgaryn — APPROVED** [review]

**Comment by rbolgaryn** [comment]
You can update the branch and we can merge this.

Please also add the mention in CHANGELOG and just in case check the text in the documentation with a spell checking tool.

**Comment by nitbharambe** [comment]
Added to changelog, updated branch and ran spellcheck. Ready for review again @rbolgaryn

**Review by rbolgaryn — APPROVED** [review]

**Pull request merged**
