### PR TITLE
Update currents.rst by providing additional information

### PR DESCRIPTION
**Pull request by sarajcev**
Updated `currents.rst` file with additional information from the `tutorial/shortcircuit.ipynb`, regarding the available short-circuit currents calculation methods. 
Merging this PR will close Issue #2054

### CODE REVIEW

**Comment by sarajcev** [comment]
Perhaps it may also be instructive to add to this file some additional information regarding the description of the results (for buses and branches) that can be obtained from the short-circuit calculations.

**Comment by rbolgaryn** [comment]
I updated some information

**Comment by rbolgaryn** [comment]
@sarajcev thak you for your contribution!

**Comment by sarajcev** [comment]
@rbolgaryn,

I'm glad I could help. This now looks great IMHO.
Do you consider this PR ready to be merged?

**Review by rbolgaryn — APPROVED** [review]

**Comment by rbolgaryn** [comment]
Yes!

**Pull request merged**
