### PR TITLE
plotting + name_display + setup.py adaption +extending .gitignore + README.rst adaptions

### PR DESCRIPTION
**Pull request by SimonRubenDrauz**
Following changes have been made:
1.) in get_collection_sizes the order of the variables was incorrect
2.) defining __str__ of a pandapower grid as __class__.__name__
3.) problems in twine --> if done with win 10 line breaks are indicated by \r\n --> \n only is required
4.) adding a folder to .gitignore --> folder which could be integrated by everyone, where files, which are confidental or which are too big, can be stored (if accepted, adapt MANIFEST.ini)
5.) changes in README.rst --> codacy and codecov

### CODE REVIEW

**Comment by SimonRubenDrauz** [comment]
io_owncloud: This was an idea if someone plans to work with big data he/she puts in a database. This would not be part of the versioning while at the same time someone has the opportunity to include this to his/her repo. Maybe another name would be moree appropriate.
\r\n: \r\n needs to be replaced in win10 as line breaks are differently interpreted. This causes problems with twine as line breaks need to be written as \n only.

**Comment by jhmenke** [comment]
>\r\n: \r\n needs to be replaced in win10 as line breaks are differently interpreted. This causes problems with twine as line breaks need to be written as \n only.

This can be automatically handled by git: https://svij.org/blog/2017/07/07/crlf-in-lf-automatisch-umwandeln-in-git-repositorys/

**Comment by SimonRubenDrauz** [comment]
other solution found --> .gitattributes were adapted! --> to consider these changes in the relevant .rst-files these files need to be modified slightly to make sure they are correctly configured in all cloned repos

**Comment by SimonRubenDrauz** [comment]
changed name of io_owncloud in data. Maybe a more appropriate name!

**Comment by lthurner** [comment]
There is a lot of back and forth in this PR and I can't really follow anymore what was changed... can you please submit a new clean PR with the final version? Thanks!

**Pull request closed without merging**
