### PR TITLE
bfswpf recycle fix #935

### LINKED ISSUE #935: Cannot use 'bfsw' algorithm with time series
I am trying to run the 'bfsw' algorithm with time series but an error occurs.

version: pandapower==2.4.0
os: #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020

What caused the error: 

I modifed this example: [Time series example](https://nbviewer.jupyter.org/github/e2nIEE/pandapower/blob/develop/tutorials/time_series.ipynb)

by changing:
```python
    # 1. create test net
    net = simple_test_net()

    # 2. create (random) data source
    n_timesteps = 24
    profiles, ds = create_data_source(n_timesteps)
    # 3. create controllers (to control P values of the load and the sgen)
    create_controllers(net, ds)

    # time steps to be calculated. Could also be a list with non-consecutive time steps
    time_steps = range(0, n_timesteps)

    # 4. the output writer with the desired results to be stored to files.
    ow = create_output_writer(net, time_steps, output_dir=output_dir)

    # 5. the main time series function
    run_timeseries(net, time_steps)
```
into

```python
def timeseries_example(output_dir):
    # 1. create test net
    net = simple_test_net()

    # 2. create (random) data source
    n_timesteps = 24
    profiles, ds = create_data_source(n_timesteps)
    # 3. create controllers (to control P values of the load and the sgen)
    create_controllers(net, ds)

    # time steps to be calculated. Could also be a list with non-consecutive time steps
    time_steps = range(0, n_timesteps)

    # 4. the output writer with the desired results to be stored to files.
    ow = create_output_writer(net, time_steps, output_dir=output_dir)

    # 5. the main time series function
    run_timeseries(net, time_steps, algorithm='bfsw')
```

Error:

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-17-7ba382adfb8e> in <module>
      3 if not os.path.exists(output_dir):
      4     os.mkdir(output_dir)
----> 5 timeseries_example(output_dir)

<ipython-input-11-b8481a2a0e9c> in timeseries_example(output_dir)
     16 
     17     # 5. the main time series function
---> 18     run_timeseries(net, time_steps, algorithm='bfsw')

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/timeseries/run_time_series.py in run_timeseries(net, time_steps, continue_on_divergence, verbose, **kwargs)
    336 
    337     control_diagnostic(net)
--> 338     run_loop(net, ts_variables, **kwargs)
    339 
    340     # cleanup functions after the last time step was calculated

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/timeseries/run_time_series.py in run_loop(net, ts_variables, **kwargs)
    308     for i, time_step in enumerate(ts_variables["time_steps"]):
    309         print_progress(i, time_step, ts_variables["time_steps"], ts_variables["verbose"], **kwargs)
--> 310         run_time_step(net, time_step, ts_variables, **kwargs)
    311 
    312 

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/timeseries/run_time_series.py in run_time_step(net, time_step, ts_variables, **kwargs)
    112     try:
    113         # calls controller init, control steps and run function (runpp usually is called in here)
--> 114         run_control(net, run_control=False, ctrl_variables=ts_variables, **kwargs)
    115     except ControllerNotConverged:
    116         ctrl_converged = False

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/control/run_control.py in run_control(net, ctrl_variables, max_iter, continue_on_lf_divergence, **kwargs)
    232 
    233     # run each controller step in given controller order
--> 234     control_implementation(controller_order, net, run_funct, errors, max_iter, continue_on_lf_divergence, **kwargs)
    235 
    236     # call finalize function of each controller

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/control/run_control.py in control_implementation(controller_order, net, run_funct, errors, max_iter, continue_on_lf_divergence, **kwargs)
    150             if not converged:
    151                 run_count += 1
--> 152                 _control_repair(net, run_funct, continue_on_lf_divergence, levelorder, errors, **kwargs)
    153         # raises controller not converged
    154         check_final_convergence(run_count, max_iter, errors, net['converged'])

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/control/run_control.py in _control_repair(net, run_funct, continue_on_lf_divergence, levelorder, errors, **kwargs)
    170 def _control_repair(net, run_funct, continue_on_lf_divergence, levelorder, errors, **kwargs):
    171     try:
--> 172         run_funct(net, **kwargs)  # run can be runpp, runopf or whatever
    173     except errors:
    174         if continue_on_lf_divergence:

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/run.py in runpp(net, algorithm, calculate_voltage_angles, init, max_iteration, tolerance_mva, trafo_model, trafo_loading, enforce_q_lims, check_connectivity, voltage_depend_loads, consider_line_temperature, run_control, **kwargs)
    223         _check_bus_index_and_print_warning_if_high(net)
    224         _check_gen_index_and_print_warning_if_high(net)
--> 225         _powerflow(net, **kwargs)
    226 
    227 

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/powerflow.py in _powerflow(net, **kwargs)
     72 
     73     # ----- run the powerflow -----
---> 74     result = _run_pf_algorithm(ppci, net["_options"], **kwargs)
     75     # read the results (=ppci with results) to net
     76     _ppci_to_net(result, net)

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/powerflow.py in _run_pf_algorithm(ppci, options, **kwargs)
    147             result = _pf_without_branches(ppci, options)
    148         elif algorithm == 'bfsw':  # forward/backward sweep power flow algorithm
--> 149             result = _run_bfswpf(ppci, options, **kwargs)[0]
    150         elif algorithm in ['nr', 'iwamoto_nr']:
    151             result = _run_newton_raphson_pf(ppci, options)

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/pf/run_bfswpf.py in _run_bfswpf(ppci, options, **kwargs)
    406 
    407         # depth-first-search bus ordering and generating Direct Load Flow matrix DLF = BCBV * BIBC
--> 408         ppci, DLF, buses_ordered_bfs_nets = _get_bibc_bcbv(ppci, options, bus, branch, G)
    409 
    410     # if there are trafos with phase-shift calculate Ybus without phase-shift for bfswpf

~/github/distflow/venv/lib/python3.8/site-packages/pandapower/pf/run_bfswpf.py in _get_bibc_bcbv(ppci, options, bus, branch, graph)
    171     recycle = options["recycle"]
    172 
--> 173     if recycle is not None and recycle["bfsw"] and ppci["internal"]["DLF"].size:
    174         DLF, buses_ordered_bfs_nets = ppci["internal"]['DLF'], \
    175                                       ppci["internal"]['buses_ord_bfs_nets']

TypeError: 'bool' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by jkrstulo**
I managed to reproduce example from #935 
I fixed it in respect to docstring of `run.runpp` which specifies `recycle` kwarg.
I am still not sure it is the best solution that it recycles according to `trafo` flag, since in bfsw algorithm it recycles specific DLF matrix. Maybe a specific flag could be introduced in the `recycled` only for bfsw?

Another thing is that `recycle` parameter in `options` is received here as boolean, which is contradictory to docstring which says `dict`? I see in auxiliary.py on line [996](https://github.com/e2nIEE/pandapower/blob/42c662ac93b652f7f615cc55f7da3603387f32a2/pandapower/auxiliary.py#L996) recycle is set to `False`, I guess there is a problem?

### CODE REVIEW

**Comment by rbolgaryn** [comment]
Hi @jkrstulo ,

thank you for the PR!

At the moment, I don't understand, why recycle is sometimes dict and sometimes True/False, and I suspect that the problem is that recycle is not set to dict but to True/False at some point in one of the previous steps.

So far, I can see that recycle can be one of the following:

* None
* True/False
* dict

In power flow (pp.runpp), it is expected that recycle is either dict or None. It means that a bug must be at an earlier point, when recycle is set to True/False.

It seems that the bug comes from Controller class, where a controller has an attribute recycle which can be True/False, and it should be fixed there.

@SimonRubenDrauz @friederikemeier @lthurner @FlorianShepherd please take a look, what do you think?

**Comment by rbolgaryn** [comment]
This PR can be merged now, and the recycle fix can be still fixed in parallel

**Comment by rbolgaryn** [comment]
#1011

**Comment by lthurner** [comment]
> It seems that the bug comes from Controller class, where a controller has an attribute recycle which can be True/False, and it should be fixed there.

I **think** True/False is an old implementation, and the dict is the new one. @FlorianShepherd should know about this.

Does this keep us from merging this PR?

**Pull request merged**
