### PR TITLE
Add python 3.10

### PR DESCRIPTION
**Pull request by rbolgaryn**

### CODE REVIEW

**Comment by rbolgaryn** [comment]
fiona 1.8.21 released yesterday, so now the support for Python 3.10 can be added

**Comment by rbolgaryn** [comment]
Dear @BDonnot ,

is it possible to add the support of Python 3.10 to lightsim2grid?

Roman

**Comment by BDonnot** [comment]
Hello,

Last time I checked, I could not do it because lightsim2grid depends on scipy which is not yet (last time I checked) compatible with python 3.10.

I'll do it as soon as scipy is supported for 3.10

**Comment by BDonnot** [comment]
Also, I run into trouble with pandapower requiring scipy <= 1.6.0 somehow.

**Comment by rbolgaryn** [comment]
> Hello,
> 
> Last time I checked, I could not do it because lightsim2grid depends on scipy which is not yet (last time I checked) compatible with python 3.10.
> 
> I'll do it as soon as scipy is supported for 3.10

On the PyPi website, it Python 3.10 is listed as supported (last release was on Friday, so maybe they added it then).

Roman

**Comment by BDonnot** [comment]
Oh ok great, I did not noticed that.

I'll see if I can installed lightsim2grid locally on a fresh python 3.10 env and if it works i'll add it to pypi asap

**Comment by BDonnot** [comment]
Lightsim2grid available for python 3.10 now :-)

**Pull request merged**
