### PR TITLE
WiP: networkx MultiGraph method edges_iter -> edges

### PR DESCRIPTION
**Pull request by miek770**
The stable version of networkx.MultiGraph uses `edges` to return the iterator, not `edges_iter`. See here: https://networkx.github.io/documentation/stable/reference/classes/multigraph.html

I would like to test this completely but I'm having issues with the compilation of graphviz, sorry. I recommend someone tests this before merging (not that it has any chance of breaking anything, but other changes might be required).

Edit: Added "WiP" for this reason (couldn't test).

Michel

### CODE REVIEW

**Comment by jhmenke** [comment]
this seems a good change, @lthurner do you agree? 
then let's merge

**Comment by lthurner** [comment]
How about backwards compatibility? Do we have a solution that is compatible with networkx 1.x and 2.x? Or is it either/or? We should be clear what versions work with pandapower and then also have this in the requirements file.

**Comment by jhmenke** [comment]
> How about backwards compatibility? Do we have a solution that is compatible with networkx 1.x and 2.x? Or is it either/or? We should be clear what versions work with pandapower and then also have this in the requirements file.

edges() in nx 2.x and edges_iter() in nx 1.x are the same as afar as i know. both return generators
edges() also exists in nx 1.x and has the same functionality, but does return a list. therefore, it is backwards compatible. the only downside might be very slight runtime increases if one still uses nx 1.x

**Comment by miek770** [comment]
Should I remove the "WiP" tag?

**Pull request merged**
