### PR TITLE
Update of the short-circuit results documentation

### LINKED ISSUE #2058: [Documentation]: Updating "bus.rst" file with SC results
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

## Labels (if access available)
* [x] Choose a `labels` at the right side (e.g. `bug`, `controller`, `OPF`...)

Documentation file "bus.rst" holds tabular descriptions of the "bus"-related results produced by the PF (i.e. `net.res_bus` and `net.res_bus_3ph`) and OPF (i.e. `net.res_bus_est`) computations. I would like to suggest augmenting this file with the tabular descriptions of the "bus"-related results provided by the short-circuit (SC) computations, i.e. adding the `net.res_bus_sc` information block.

If this is something desirable, I would like to follow up on this issue by opening a PR with this implementation. This could be then followed up by implementing the same information regarding the "line" (i.e. `net.res_line_sc`) and transformers.

Any suggestions on this issue would be most appreciated.

CC @rbolgaryn

### PR DESCRIPTION
**Pull request by sarajcev**
This PR closes #2058. 

It adds tabular descriptions of parameters for the short-circuit results: `net.res_bus_sc`, `net.res_line_sc` and `net.res_trafo_sc` to their appropriate documentation files (along with the associated CSV files). This is a continuation of the improvement of the short-circuit analysis documentation initiated in #2054. 

Looking forward to the comments and reviews.

CC @rbolgaryn

### CODE REVIEW

**Comment by rbolgaryn** [comment]
Dear @sarajcev ,

thank you for your contribution!

What do you think about the comments?

Best regards,
Roman

**Comment by sarajcev** [comment]
Hi @rbolgaryn,
I'm fine with everything. If there is anything else you would like to see as part of this PR, please feel free to comment and I will try to add it?
Kind regards,
Peter

**Comment by sarajcev** [comment]
Hi @rbolgaryn, 
I have added the documentation for the `net.res_trafo3w_sc` as part of this PR, so that the set of SC results is complete now.
Looking forward to your review.
Best regards,
Peter

**Comment by sarajcev** [comment]
Hi @rbolgaryn, 
this is just a reminder so that this PR does not become stale. Do you consider this ready for merging or is there anything else you would like to see included?
Thanks in advance.
Best regards,
Peter

**Comment by rbolgaryn** [comment]
Hi @sarajcev ,

I apologize for not replying earlier - I was on vacation.

Thank you very much for your contribution!

Please address the comments above, and resolve the conflict - then from my point of view it is ready to merge.

Best regards,
Roman

**Comment by sarajcev** [comment]
Hi @rbolgaryn, 
I've resolved a conflict in CHANGELOG.rst. I haven't seen any other comments (am I missing something?).
Looking forward to your feedback.
Best regards,
Peter

**Comment by rbolgaryn** [comment]
> Hi @rbolgaryn, I've resolved a conflict in CHANGELOG.rst. I haven't seen any other comments (am I missing something?). Looking forward to your feedback. Best regards, Peter

grafik

I meant these comments

**Comment by sarajcev** [comment]
Hi @rbolgaryn,
sorry for the confusion. I've pushed the code with requested changes, although I can't seem to find these comments under the code review? 
Does this addresses the issues?
Thanks for your patience.
Kind regards,
Peter

**Review by rbolgaryn — APPROVED** [review]

**Comment by sarajcev** [comment]
Hi @rbolgaryn, 

I was able to find the comments, after all. :-)

I enjoyed taking part in this and working with you, and I hope I'll be able to contribute again. Thanks for the help.

Best regards,
Peter

**Pull request merged**
