### PR TITLE
Feature: allow passing custom runpp-function to pp.diagnostics

### PR DESCRIPTION
**Pull request by jthurner**
`pp.diagnostic` runs power flows during various tests but does not allow passing arguments to `pp.runpp`. 

This PR adds an optional argument `runpp_function` to `pp.diagnostic` which takes a function to be used for running power flows. The argument defaults to `pp.runpp`, existing code is unaffected.

Arguments to `pp.runpp` can then be passed through `pp.diagnostic` by supplying a partial as the `runpp_function`.

### CODE REVIEW

**Review by rbolgaryn — CHANGES_REQUESTED** [review]
Dear @jthurner ,

thank you for this contribution!

I suggest enabling two features: 1) passing the function to be used instead of runpp and 2) passing kwargs to that function - in a way that either one is possible and you do not need to prepare the partial for the diagnostic function.

e.g. 

diagnostic(net, init="results")
diagnostic(net, runpp_function=pp.rundcpp)
diagnostic(net, runpp_function=pp.rundcpp, trafo_loading="power")

Also, I suggest renaming the parameter to "run" to be consistent with the pp.run_timeseries where you can pass the runpp function as the "run" parameter.

**Comment by jthurner** [comment]
Dear Roman,
the signature should now be consistent with pp.run_timeseries, please check if these changes are what you had in mind.

**Comment by rbolgaryn** [comment]
Dear @jthurner ,

please update the branch (merge develop) and add a mention of this change to CHANGELOG.

**Comment by rbolgaryn** [comment]
for some reason I cannot update the branch (usually there is a button "Update branch" but not in this case)

**Comment by jthurner** [comment]
Merged develop and updated CHANGELOG.

> for some reason I cannot update the branch (usually there is a button "Update branch" but not in this case)

Because the fork is under an organization account, I can not grant "Allow edits from maintainers" on the PR (see e.g.  
[orgs/community#5634](https://github.com/orgs/community/discussions/5634)).  Pretty annoying, we might have to  open future PRs from personal branches instead.

**Review by rbolgaryn — APPROVED** [review]

**Pull request merged**
