### PR TITLE
New explicit current source parameter for sgen

### PR DESCRIPTION
**Pull request by miek770**
Following the conclusion of #240, here's a working WiP. I think the only missing piece is the adjustment of the json and pickle test networks to include this new column.

Any comment on the current changes? Am I missing something else?

P.S.: Pytest reports: 5 failed, 313 passed, 3 xfailed, 2676 warnings in 259.38 seconds. The 5 failed tests are from test_meshing_detection.py (pickle) and test_1ph.py (json).

Thanks.

### CODE REVIEW

**Comment by miek770** [comment]
Today's commit fixes the json and pickle. Should be ready to merge. I closed #240.

Comments welcome.

**Comment by lthurner** [comment]
Sorry for only looking into this now. Thanks for the contribution, looks fine all around! Only two things:
1. When we change parameters in the network we include these changes in the convert_format function. This function is always called when networks are loaded from the hard drive. That way, networks that are saved with an older version of pandapower can always be loaded and used without having to change the file.
2. Can you please add these changes on the dev_2.0 branch? I have made some changes in this branch that would be difficult to merge this commit, so adding them directly in dev_2.0 would be preferred. We will sone merge dev_2.0 into develop to not have to much duplication...

**Comment by miek770** [comment]
Ok no problem, I'll do it.

**Comment by miek770** [comment]
Replaced by #250, closing.

**Pull request closed without merging**
