### PR TITLE
Faster graph creation

### PR DESCRIPTION
**Pull request by WinfriedL**
I changed the implementation for the `create_graph()` function to iterate over the dataframes and add single edges for each branch. On my machine and testcase this speeds up the graph creation from about 110ms to 90ms and has in my opinion some other advantages:
- The code is more readable
- More flexible to add/change weights
- Easier to make it configurable

I believe the reason for the speed improvement is that networkx `add_edges_from()` more or less only iterates over the list of edges and calls `add_egde()` with the appropriate parameters. So instead of creating lists of edges with complex zip() calls only to iterate over it anyway can be replaced by iterating over the dataframes and call `add_edge()` directly.

However, before thinking about merging this, there probably should be a decision about #85, as you can see by acd4d3cf48fcd04f342265c1ccc9a7fb8e6bfb88

### CODE REVIEW

**Comment by lthurner** [comment]
This issue is further complicated by the fact that networkx 1.x and 2.x have some significant differences in the internal data structure with regard to the attributes. We have tried to write the code so that it is compatible with both versions, but maybe we should ditch 1.x support and just switch to 2.x.

Also all tests are passing, but I am not sure how good the test suite for the graph creation functions are? We should also check that before refactoring...

**Comment by WinfriedL** [comment]
> Also all tests are passing, but I am not sure how good the test suite for the graph creation functions are? We should also check that before refactoring...

That seems like a good idea. Also having some test if the calculation of the additional weights from #120 is correct would be great. I am not sure if I have the time though.

I checked that for my network both implementations result in the same edges with the same attributes and values of the attributes. If I recall correctly the order of the edges is different for three winding transformer, but that should not matter.

**Comment by lthurner** [comment]
I merged this into the dev_2.0 branch now. Regarding the testing of the impedance values:

> Also having some test if the calculation of the additional weights from #120 is correct would be great. I am not sure if I have the time though.

Couldn't we just call the functions from build_branch.py that calculate the impedances instead of reimplementing the functions in create_graph?

**Comment by WinfriedL** [comment]
> Couldn't we just call the functions from build_branch.py that calculate the impedances instead of reimplementing the functions in create_graph?

This would be a good idea, but the impedance values calculated in build_branch.py are in pu, while here they are calculated in ohm.

I have to think about if this would matter for my usecase (maybe not).

 In a way I was going in this direction anyway, since I experimented with creating the graph from the ppci which is drastically faster than using the pandapower net. (I have 200k buses in the pandapower net, but since most of them are auxiliary switch buses, I end up with 15k buses in the ppci)

**Comment by lthurner** [comment]
> This would be a good idea, but the impedance values calculated in build_branch.py are in pu, while here they are calculated in ohm.

Thats true, but the pu conversion is also done in the current solution:

https://github.com/e2nIEE/pandapower/blob/b780d1cbacf9ae406c18d3ac4f6ed9b2ba3e89ff/pandapower/topology/create_graph.py#L125-L130

> In a way I was going in this direction anyway, since I experimented with creating the graph from the ppci which is drastically faster than using the pandapower net. (I have 200k buses in the pandapower net, but since most of them are auxiliary switch buses, I end up with 15k buses in the ppci)

There is definitely a lot of room for performance improvement in the current implementation. itertuples is significantly faster than iterrows, but iterating over multiple numpy arrays with zip would definitely still be a lot faster (although the code wouldn't be as elegant)

**Comment by WinfriedL** [comment]
> Thats true, but the pu conversion is also done in the current solution

Ok, one could of course use build_branch for the pu values an then convert them back to ohm

>There is definitely a lot of room for performance improvement in the current implementation.

Probably. I am still too much used to pandas instead of numpy.

**Pull request closed without merging**
