### PR TITLE
Fixed bug #858, Fixed bug #763, Simplified results checkout and simplfied the pd2ppc measurement conversion

### PR DESCRIPTION
**Pull request by wangzhenassd**

### CODE REVIEW

**Comment by wangzhenassd** [comment]
@jhmenke Can you review this regarding pp2ppc conversion and the result checkout? Because I also tried to fix the initialization with results, maybe it makes sense to skip rename res_x to res_x_power_flow, since state estimation results are saved in res_x_est directly.

**Comment by wangzhenassd** [comment]
@FlorianShepherd can you help me review the build_bus and the relevant test part? There was a userwarning in the code but never raised. Thanks a lot!

**Comment by wangzhenassd** [comment]
@FlorianShepherd It seems the control test does not work with pandas 1.1.0, can you repair this?

**Comment by jhmenke** [comment]
Code looks okay if the tests pass (although you made some changes to them).

Some remarks regarding coding style:

```
if net.measurement.empty:
        raise AssertionError("Measurement cannot be empty!")
```

Why have you refactored it? This is the same and looks cleaner:

`assert not net.measurement.empty, "Measurement cannot be empty!"`

Similarly, Python3 styleguide recommends not using % and instead .format or f strings:

`res_element_with_suffix, "_empty_%s" % res_element`

`res_element_with_suffix, "_empty_{}".format(res_element)`
`res_element_with_suffix, f"_empty_{res_element}"`

**Comment by wangzhenassd** [comment]
@jhmenke Thank you for the review!

This is because of the Codacy Quality Review, the usage of "assert" is categorized as possible issue, that's why I switched the styling to if ... raise...

You are right, I think also f-string is the most elegant way. But Py35 does not support f-string. Maybe we can consider drop support of py35 and also update other places which used the old '%' style, since library like pandas will release no more version for py35.

**Pull request merged**
