### PR TITLE
Fix tap_dependent_impedance for trafo3w

### PR DESCRIPTION
**Pull request by bramstoeller**
Fixes https://github.com/e2nIEE/pandapower/issues/1831

### CODE REVIEW

**Comment by rbolgaryn** [comment]
Dear @bramstoeller ,

tnak you for identifying the issue and opening this pull request!

Please also add a mention of this change in the file CHANGELOG.rst

Best regards,
Roman

**Comment by bramstoeller** [comment]
@rbolgaryn I've added the bugfix to the readme, could you review this PR again?

**Comment by bramstoeller** [comment]
Ok, fair enough. It is currently blocking one of our unit tests, but we can live with that.
https://github.com/alliander-opensource/power-grid-model-io/blob/release/pp/tests/unit/converters/test_pandapower_converter.py#L418-L431

**Comment by rbolgaryn** [comment]
We will fix it on develop at first: https://github.com/e2nIEE/pandapower/pull/1845

We will have a new release with the fix some time later

**Comment by rbolgaryn** [comment]
Dear @bramstoeller ,

The issue is fixed on develop branch. Please stay put until the next release, and use the develop branch in the meantime.

Best regards,
Roman

**Pull request closed without merging**
