### PR TITLE
infer types of columns in available std_types

### PR DESCRIPTION
**Pull request by dlohmeier**

### CODE REVIEW

**Comment by lthurner** [comment]
Why not use convert_objects in the except statement?

**Comment by dlohmeier** [comment]
@lthurner this could be done, but would throw a FutureWarning starting from pandas 0.17, whereas infer_types was only introduced in pandas 0.21. That wouldn't really look nice for the user and might even be confusing. How could this be dealt with?

**Comment by lthurner** [comment]
imho it is better to "risk" throwing a future warning than to have different behaviour/output of the function depending on the pandas version

**Comment by dlohmeier** [comment]
I now prevented this behavior with the help of ignoring warnings temporarily. For that I will open a new pull request.

**Pull request merged**
