### PR TITLE
Additional patches for plotter

### PR DESCRIPTION
**Pull request by hzraja**
- [x] Added patch for the Wind turbine
- [x] Added patch for PV
- [x] static alignment for generic patches based on the different patch type at each bus (3 patches -> 120°, 4 patches -> 90°)
- [x] Fix visual Bugs
- [x] Add changes to` \pandapower\CHANGELOG.rst`

### CODE REVIEW

**Comment by hzraja** [comment]
New_patches

**Review by jwiemer112 — APPROVED** [review]

**Review by jwiemer112 — COMMENTED** [review]
finnish bugs fixing

**Comment by hzraja** [comment]
> finnish bugs fixing

**Review by jwiemer112 — APPROVED** [review]

**Comment by jkisse** [comment]
This PR causes inconsistencies with pandapipes, i.e. the test are failing. Could you please repair that?

**Pull request merged**
