### PR TITLE
Feature/dump_to_geojson

### PR DESCRIPTION
**Pull request by KS-HTK**
added a function to dump all lines and buses to geojson

this differs from using `convert_geodata_to_gis` and then `bus_geodata.to_json()` as all values from 'bus' and 'res_bus'/ 'line' and 'res_line' tables are added as properties to the geojson feature

EDIT:
also added a function convert_crs to convert geodata between coordinate reference systems.
GeoJSON should always contain WGS84 geodata so this function is necessary.

### CODE REVIEW

**Comment by KS-HTK** [comment]
I have updated this PR to include support for pandapipes networks.
I decided against implementing it twice since pandapipes.plotting.geo imports pandapower.plotting.geo anyway and therefore can just import the function from here.

**Comment by jwiemer112** [comment]
Just a reminder ... 

We plan to release **pandapower 2.13.0 at friday the 12.05.2023**. Maybe that's a nice oppurtunity to finish this PR. =)

**Comment by KS-HTK** [comment]
@jwiemer112 This has not jet been merged. Am I missing something you were expecting to be part of this PR?

**Comment by jwiemer112** [comment]
> @jwiemer112 This has not jet been merged. Am I missing something you were expecting to be part of this PR?

Hey @KS-HTK

thanks for your implementations.

As I wrote, it was just a reminder to finish open PR's. So your PR is ready and can be merged, as I read from your comments. Only a review is missing. I asked mike and alex to review your implementations.

Greetz Jan

**Review by vogt31337 — DISMISSED** [review]
Looks fine to me.

**Review by jwiemer112 — APPROVED** [review]

**Pull request merged**
