### PR TITLE
Update run_time_series.py

### PR DESCRIPTION
**Pull request by rbolgaryn**
cleanup: remove ppc from net to address the unexpected recycle behavior

### CODE REVIEW

**Comment by rbolgaryn** [comment]
some context: timeseries simulation had some very confusing inconsistent behavior. 
If recycle=True and continue_on_divergence=False, and a time step led to net not converging, the error was ignored and all the subsequent time steps had either NaN or the same values as the last successful time step. 

If the same timeseries simulation was repeated, the first time step failed already. All the time steps had NaN.

If continue_on_divergence=True, all the time steps failed after the first failing time step (unlike with recycle=False).

As a workaround, here we set net._ppc to None if a time step fails, to trigger a "normal" power flow calculation (without recycle) for the next time step. Besides, we also set net._ppc to None after the timeseries calculation is complete.

This fixes the most urgent issues with recycle. 

But there is still the following issue: if recycle=True and continue_on_divergence=True and init="results", the calculation fails, even though it works with recycle=False. 

Also, we still need to understand the root cause of this behavior.

We need to write more tests for the recycle feature.

**Comment by rbolgaryn** [comment]
the cleanup function in pandapipes would also need to be modified

**Comment by SimonRubenDrauz** [comment]
In pandapipes there

> 

I pandapipes there is no recycle option so far. So I guess, this should not cause any problems!

**Comment by rbolgaryn** [comment]
> > the cleanup function in pandapipes would also need to be modified
> 
> I pandapipes there is no recycle option so far. So I guess, this should not cause any problems!

The cleanup receives net as the first input parameter in this PR, so it also affects pandapipes when the function cleanup is used.

**Comment by rbolgaryn** [comment]
> > the cleanup function in pandapipes would also need to be modified
> 
> I pandapipes there is no recycle option so far. So I guess, this should not cause any problems!

Here is where the error in pandapipes happens:

```python
        # cleanup functions after the last time step was calculated
>       cleanup(ts_variables)
E       TypeError: cleanup() missing 1 required positional argument: 'ts_variables'
```

**Pull request merged**
