### PR TITLE
add SimBench grid dataset and code

### PR DESCRIPTION
**Pull request by SteffenMeinecke**

### CODE REVIEW

**Comment by FlorianShepherd** [comment]
@jhmenke  noted that this would increase the size of the repo by more than 10% to 527MB from 473 MB. Should we really integrate all that in pp main? Another idea would be to have a submodule for simbench.

**Comment by jhmenke** [comment]
Two options:
- Integrate simbench directly into the pandapower repo (size of simbench folder: 410 MB)
- Create a separate repo for simbench grid data (could be included as git submodule in pandapower). could also be a pip package, e.g., pandapower-simbench with pandapower as requirement

**Comment by FlorianShepherd** [comment]
> Two options:
> 
>     * Integrate simbench directly into the pandapower repo (size of simbench folder: 410 MB vs 20 MB for all other grids)
> 
>     * Create a separate repo for simbench grid data (could be included as git submodule in pandapower). could also be a pip package, e.g., pandapower-simbench with pandapower as requirement

I vote for the second option with a sub-repo

**Comment by jhmenke** [comment]
let's discuss this at the next pandapower meeting

**Comment by FlorianShepherd** [comment]
Here some infos on submodules:
https://github.blog/2016-02-01-working-with-submodules/

**Comment by lthurner** [comment]
Discussed today: add the data in a sperate repository, and make the module "pandapower-simbench" pip installable. This new module gets a seperate documentation that details how to integate the simbench grids into pandapower.

**Pull request closed without merging**
